apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: glagol-io-deploy
  labels:
    revision: ${REVISION}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glagol-io
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: glagol-io
        revision: ${REVISION}
    spec:
      containers:
      - name: glagol-io-pod
        image: "glagol/glagol.io:dev-master"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: APP_ENV
          value: production
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: glagol-io
              key: app_key
        - name: PASSWORD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: glagol-io
              key: client_id
        - name: PASSWORD_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: glagol-io
              key: client_secret
        - name: APP_DEBUG
          value: '0'
        - name: APP_TIMEZONE
          value: UTC
        - name: DB_CONNECTION
          value: mysql
        - name: DB_HOST
          value: '127.0.0.1'
        - name: DB_PORT
          value: '3306'
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: ssh-tunnel
              key: db_name
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: CACHE_DRIVER
          value: array
        - name: QUEUE_DRIVER
          value: sync
        - name: LOG_CHANNEL
          value: syslog
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=glagol-cloud:europe-west4:glagol-cloud-rdb=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials