version: '3'
services:
  php:
    image: glagol.io
    build: .
    command: --dev
    volumes:
      - ./.cache/composer:/root/.composer/cache
      - ./app/:/var/www/html
    ports:
      - 80:80
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      #APP_KEY:
      APP_TIMEZONE: UTC
      LOG_CHANNEL: syslog
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: glagol
      DB_USERNAME: root
      DB_PASSWORD: 123
      CACHE_DRIVER: array
      QUEUE_DRIVER: sync
    links:
      - database
  database:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: glagol
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

